import ProductCard from "@/app/_components/ProductCard/ProductCard";
import { getAllProducts, getProductByCategory } from "@/serverAPIs/products.api";
import { getAllCategories } from "@/serverAPIs/Categories";
import GsapStagger from "@/components/shared/GsapStagger";
import PageWrapper from "@/components/shared/PageWrapper";
import { SlidersHorizontal, Check, LayoutGrid as Grid, ShoppingBag } from "lucide-react";
import Link from "next/link";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

interface PageProps {
  searchParams: Promise<{ category?: string }>;
}

export default async function Products({ searchParams }: PageProps) {
  const resolvedSearchParams = searchParams ? (await searchParams) : {};
  const activeCategoryId = resolvedSearchParams?.category;

  const [products, categories] = await Promise.all([
    activeCategoryId ? getProductByCategory(activeCategoryId) : getAllProducts(),
    getAllCategories(),
  ]);

  const activeCategory = categories.find((cat) => cat._id === activeCategoryId);

  return (
    <PageWrapper>
      <div className="container mx-auto w-[95%] lg:w-[90%] my-10">
        {/* Page Breadcrumb / Title */}
        <div className="mb-8">
          <nav className="flex mb-3 text-xs md:text-sm font-medium text-gray-500">
            <ol className="flex items-center space-x-2">
              <li>
                <Link href="/" className="hover:text-green-600 transition-colors">Home</Link>
              </li>
              <li>/</li>
              <li>
                <Link href="/products" className="hover:text-green-600 transition-colors">Products</Link>
              </li>
              {activeCategory && (
                <>
                  <li>/</li>
                  <li className="text-gray-700 font-medium line-clamp-1">{activeCategory.name}</li>
                </>
              )}
            </ol>
          </nav>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-3xl font-extrabold tracking-tight text-gray-900">
                {activeCategory ? activeCategory.name : "Popular Products"}
              </h1>
              <p className="mt-1.5 text-sm text-gray-500">
                {activeCategory 
                  ? `Discover our exclusive collection of ${activeCategory.name.toLowerCase()}` 
                  : "Explore our wide range of premium products selected just for you."
                }
              </p>
            </div>
            <div className="text-xs md:text-sm text-gray-500 font-medium self-end md:self-auto bg-gray-50 px-3 py-1.5 rounded-lg border border-gray-100 shrink-0">
              Showing <span className="font-bold text-gray-900">{products.length}</span> products
            </div>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-8 items-start">
          {/* LEFT SIDEBAR (Desktop) */}
          <aside className="hidden md:block w-64 shrink-0 sticky top-24 bg-white border border-gray-100 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center gap-2 pb-4 mb-4 border-b border-gray-100">
              <span className="p-1.5 rounded-lg bg-green-50 text-green-600">
                <SlidersHorizontal className="h-4 w-4" />
              </span>
              <h3 className="font-bold text-gray-900 text-xs tracking-wide uppercase">Categories</h3>
            </div>
            
            <div className="space-y-1">
              <Link 
                href="/products" 
                className={`flex items-center justify-between px-3.5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 group ${
                  !activeCategoryId 
                    ? "bg-green-600 text-white shadow-md shadow-green-100" 
                    : "text-gray-600 hover:bg-gray-50 hover:text-green-600"
                }`}
              >
                <div className="flex items-center gap-2.5">
                  <Grid className="h-4 w-4 shrink-0" />
                  <span>All Products</span>
                </div>
                {!activeCategoryId && <Check className="h-4 w-4 shrink-0 text-white" />}
              </Link>

              {categories.map((category) => {
                const isActive = activeCategoryId === category._id;
                return (
                  <Link 
                    key={category._id} 
                    href={`/products?category=${category._id}`} 
                    className={`flex items-center justify-between px-3.5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 group ${
                      isActive 
                        ? "bg-green-600 text-white shadow-md shadow-green-100" 
                        : "text-gray-600 hover:bg-gray-50 hover:text-green-600"
                    }`}
                  >
                    <span className="truncate">{category.name}</span>
                    {isActive && <Check className="h-4 w-4 shrink-0 text-white" />}
                  </Link>
                );
              })}
            </div>
          </aside>

          {/* HORIZONTAL CATEGORY SCROLLBAR (Mobile/Tablet) */}
          <div className="md:hidden w-full overflow-x-auto pb-3 mb-2 scrollbar-none flex gap-2">
            <Link 
              href="/products" 
              className={`shrink-0 px-4 py-2 rounded-full text-xs font-bold border transition-all ${
                !activeCategoryId 
                  ? "bg-green-600 text-white border-green-600 shadow-sm" 
                  : "bg-white text-gray-600 border-gray-200 hover:border-green-600 hover:text-green-600"
              }`}
            >
              All Products
            </Link>
            {categories.map((category) => {
              const isActive = activeCategoryId === category._id;
              return (
                <Link 
                  key={category._id} 
                  href={`/products?category=${category._id}`} 
                  className={`shrink-0 px-4 py-2 rounded-full text-xs font-bold border transition-all ${
                    isActive 
                      ? "bg-green-600 text-white border-green-600 shadow-sm" 
                      : "bg-white text-gray-600 border-gray-200 hover:border-green-600 hover:text-green-600"
                  }`}
                >
                  {category.name}
                </Link>
              );
            })}
          </div>

          {/* MAIN PRODUCT LIST */}
          <div className="flex-1 w-full">
            {products.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 px-4 bg-gray-50/50 border border-dashed border-gray-200 rounded-2xl">
                <ShoppingBag className="h-12 w-12 text-gray-400 mb-3" />
                <h3 className="text-lg font-bold text-gray-900 mb-1">No products found</h3>
                <p className="text-sm text-gray-500 text-center max-w-sm">
                  We couldn't find any products in this category. Try selecting another one or check back later!
                </p>
                <Link 
                  href="/products" 
                  className="mt-4 px-4 py-2 text-xs font-bold text-white bg-green-600 hover:bg-green-700 rounded-lg transition-colors"
                >
                  View All Products
                </Link>
              </div>
            ) : (
              <GsapStagger key={activeCategoryId ?? "all"} className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4" staggerAmount={0.04}>
                {products.map((product) => (
                  <ProductCard product={product} key={product._id} />
                ))}
              </GsapStagger>
            )}
          </div>
        </div>
      </div>
    </PageWrapper>
  );
}
