import { WishlistState } from '@/app/(platform)/wishlist/Store/Slice.wishlist';
import Providers from "@/components/providers/providers";
import { verifyToken } from "@/Cookies/auth.actions";
import { getLoggedUserCart } from "@/serverAPIs/CartActions";
import { GetLoggedUserWishlist } from "@/serverAPIs/WishlistActions";
import type { Metadata } from "next";
import { Exo, Geist, Geist_Mono } from "next/font/google";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css';
import "../styles/globals.css";
import { CartState } from "./(platform)/cart/Store/slice.cart";
import Footer from "./_components/Footer/Footer";
import Navbar from "./_components/NavBar/Navbar";

const exo = Exo({
  subsets:['latin'],
  weight:['400','500','600','700','800','900'],
  variable:'--font-exo'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce ",
  description: "Generated by create next app",
};

let cartState:CartState = {
  cartId: null,
  products: [],
  totalCartPrice: 0,
  numOfCartItems: 0,
  error: null,
  IsLoading: false,
}
    let wishlistState:WishlistState={
    status: "success",
    count: 0,
    data: [] ,
}



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const response = await verifyToken();
  if(response.isAuthenticated){
    const cart = await getLoggedUserCart();
    cartState={
      cartId: cart.cartId,
      products: cart.data.products,
      totalCartPrice: cart.data.totalCartPrice,
      numOfCartItems: cart.numOfCartItems,
      error: null,
      IsLoading: false,
    }
    const wishlist = await GetLoggedUserWishlist();
    wishlistState={
      status: wishlist.status,
      count: wishlist.count,
      data: wishlist.data,
    }

  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${exo.className}`}
        cz-shortcut-listen=""
      >
          <Providers preloadedState={{auth:response, cart:cartState,wishlist:wishlistState}}>
            <Navbar/>
            {children}
            <Footer/>
          </Providers>

          
      </body>
    </html>
  );
}
