
import ProductDetails from '@/app/_components/ProductDetails/ProductDetails';
import { getProductDetails } from '@/serverAPIs/products.api';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Details",
  description: "Generated by create next app",
};

export default async function page({params}:{params: {id:string}}) {
    const {id} =await params;


    const productDetails = await getProductDetails(id);
    
return <>
<ProductDetails productDetails={productDetails} />
</>

}
